In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
from pathlib import Path

from brain_image.data import load_eeg_data

eeg_data, times, channel_names = load_eeg_data(
    Path("data/things-eeg2/eeg/sub-01/preprocessed_eeg_training.npy")
)

print(eeg_data.shape)
print(times.shape)
print(channel_names)

torch.Size([16540, 4, 17, 100])
torch.Size([100])
['Pz', 'P3', 'P7', 'O1', 'Oz', 'O2', 'P4', 'P8', 'P1', 'P5', 'PO7', 'PO3', 'POz', 'PO4', 'PO8', 'P6', 'P2']


In [3]:
import numpy as np
from scipy.interpolate import interp1d

print(eeg_data.shape)

x1 = np.linspace(0, 1, eeg_data.shape[-1])
x2 = np.linspace(0, 1, 128)
f = interp1d(x1, eeg_data, axis=-1)
f(x2)

torch.Size([16540, 4, 17, 100])


array([[[[-8.04186940e-01, -4.88546091e-01, -1.32524585e-01, ...,
          -6.06421042e-01, -2.31188364e-01,  3.52179408e-02],
         [-7.82207310e-01, -4.86709464e-01, -2.42300058e-01, ...,
          -1.69887425e+00, -2.01548346e+00, -2.24008060e+00],
         [-1.66649830e+00, -1.66198652e+00, -1.63445376e+00, ...,
           6.88936286e-01,  1.58199389e-01, -4.64534193e-01],
         ...,
         [ 1.37716055e-01,  2.56790992e-01, -8.43344758e-03, ...,
           8.08898201e-02, -1.98680226e-01, -4.94730197e-01],
         [ 5.26930511e-01,  3.54054623e-01, -2.36190797e-03, ...,
          -2.73172735e-01, -2.00944735e-01, -6.34345710e-02],
         [-1.41619623e-01, -5.30451321e-02,  1.22133063e-01, ...,
           7.41812201e-02,  1.61726866e-01,  4.67900552e-01]],

        [[ 8.69914055e-01,  9.29696084e-01,  9.95444934e-01, ...,
           1.55720592e-01,  5.56141298e-01,  8.99504364e-01],
         [ 5.71233094e-01,  4.89027704e-01,  4.88403358e-01, ...,
          -1.12042797e

In [4]:
import torch


torch.nn.functional.interpolate(eeg_data, size=(17, 128), mode="nearest")

tensor([[[[-8.0419e-01, -8.0419e-01, -3.9927e-01,  ..., -8.4295e-01,
           -3.0654e-01,  3.5218e-02],
          [-7.8221e-01, -7.8221e-01, -4.0313e-01,  ..., -1.4993e+00,
           -1.9520e+00, -2.2401e+00],
          [-1.6665e+00, -1.6665e+00, -1.6607e+00,  ...,  9.6863e-01,
            3.3433e-01, -4.6453e-01],
          ...,
          [ 1.3772e-01,  1.3772e-01,  2.9047e-01,  ...,  2.3535e-01,
           -1.1495e-01, -4.9473e-01],
          [ 5.2693e-01,  5.2693e-01,  3.0516e-01,  ..., -2.9947e-01,
           -2.3984e-01, -6.3435e-02],
          [-1.4162e-01, -1.4162e-01, -2.7994e-02,  ...,  7.3431e-02,
            7.5132e-02,  4.6790e-01]],

         [[ 8.6991e-01,  8.6991e-01,  9.4660e-01,  ..., -8.3508e-02,
            4.5903e-01,  8.9950e-01],
          [ 5.7123e-01,  5.7123e-01,  4.6578e-01,  ..., -1.0921e+00,
           -1.1564e+00, -7.1643e-01],
          [-9.6206e-01, -9.6206e-01, -7.0451e-01,  ..., -8.5277e-02,
           -2.9733e-01, -8.2271e-01],
          ...,
     

In [12]:
from brain_image.data import preprocess_eeg_data

preprocess_eeg_data(eeg_data, interpolate_size=(17, 256))

torch.Size([16540, 4, 17, 256])


tensor([[[-0.1357, -0.1357, -0.1357,  ...,  0.2748,  0.4957,  0.4957],
         [-0.2507, -0.2507, -0.2507,  ..., -0.8518, -0.7414, -0.7414],
         [-1.0719, -1.0719, -1.0719,  ..., -1.2197, -1.8658, -1.8658],
         ...,
         [-0.0515, -0.0515, -0.0515,  ..., -0.4597, -0.4851, -0.4851],
         [-0.4313, -0.4313, -0.4313,  ..., -0.7120, -0.5498, -0.5498],
         [-0.2182, -0.2182, -0.2182,  ..., -0.1377,  0.0872,  0.0872]],

        [[ 0.1266,  0.1266,  0.1266,  ...,  1.0907,  0.7595,  0.7595],
         [-0.4898, -0.4898, -0.4898,  ..., -0.2135,  0.3753,  0.3753],
         [-0.5372, -0.5372, -0.5372,  ..., -1.0449, -0.3676, -0.3676],
         ...,
         [ 0.3809,  0.3809,  0.3809,  ..., -0.1584, -0.5118, -0.5118],
         [ 0.6128,  0.6128,  0.6128,  ..., -1.2089, -0.9845, -0.9845],
         [ 0.2655,  0.2655,  0.2655,  ...,  0.2549,  0.0518,  0.0518]],

        [[ 0.2366,  0.2366,  0.2366,  ...,  0.1055,  0.3324,  0.3324],
         [ 0.3453,  0.3453,  0.3453,  ..., -0

In [72]:
# Get the eeg model
from brain_image.model import EEGEncoder, EEGEncoderConfig


ex_batch = preprocess_eeg_data(eeg_data[:16], interpolate_size=None)

eeg_encoder_config = EEGEncoderConfig(
    f1=64,
    f2=64,
    embed_dim=40,
    pool1=2,
    stride1=2,
    pool2=1,
    stride2=1,
    kernel1=29,
    kernel2=17,
)
eeg_encoder = EEGEncoder(config=eeg_encoder_config)

eeg_encoder(ex_batch).shape

(debug): 0 - torch.Size([16, 64, 17, 72]) - layer_0
(debug): 1 - torch.Size([16, 64, 17, 72]) - layer_1
(debug): 2 - torch.Size([16, 64, 17, 72]) - layer_2
(debug): 3 - torch.Size([16, 64, 17, 72]) - layer_3
(debug): 4 - torch.Size([16, 64, 17, 36]) - layer_4
(debug): 5 - torch.Size([16, 64, 1, 36]) - layer_5
(debug): 6 - torch.Size([16, 64, 1, 36]) - layer_6
(debug): 7 - torch.Size([16, 64, 1, 36]) - layer_7
(debug): 8 - torch.Size([16, 64, 1, 36]) - layer_8
(debug): 9 - torch.Size([16, 64, 1, 36]) - layer_9
(debug): 10 - torch.Size([16, 40, 1, 36]) - layer_10


torch.Size([16, 1440])